version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: paperpal-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env    # ✅ make sure .env is visible inside the container
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: paperpal-frontend
    env_file:
      - ./backend/.env
    environment:
      - BACKEND_BASE_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always   # ✅ fix typo (was "alway")
