services:
  # 🧠 Backend (FastAPI)
  - type: web
    name: paperpal-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: APP_NAME
        value: paperpal
      - key: APP_ENV
        value: prod
      - key: MONGODB_URI
        sync: false      # secure: will set in dashboard
      - key: MONGODB_DB
        value: paperpal_db
      - key: FRONTEND_ORIGIN
        value: https://paperpal-frontend.onrender.com

  # 🎨 Frontend (Streamlit)
  - type: web
    name: paperpal-frontend
    env: python
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    plan: free
    envVars:
      - key: BACKEND_BASE_URL
        value: https://paperpal-backend.onrender.com
      - key: API_PREFIX
        value: /api/v1
      - key: API_UPLOAD_ROUTE
        value: /papers/upload
